#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

cmake_policy(SET CMP0012 NEW) # new policy for the if that evaluates a boolean out of "if(NOT ${same_location})"

function(ly_copy source_file target_directory)
    cmake_path(GET source_file FILENAME target_filename)
    cmake_path(APPEND target_file "${target_directory}" "${target_filename}")
    cmake_path(COMPARE "${source_file}" EQUAL "${target_file}" same_location)
    if(NOT ${same_location})
        file(LOCK "${target_file}.lock" GUARD FUNCTION TIMEOUT 300)
        file(SIZE "${source_file}" source_file_size)
        if(EXISTS "${target_file}")
            file(SIZE "${target_file}" target_file_size)
        else()
            set(target_file_size 0)
        endif()
        if((NOT source_file_size EQUAL target_file_size) OR "${source_file}" IS_NEWER_THAN "${target_file}")
            message(STATUS "Copying \"${source_file}\" to \"${target_directory}\"...")
            file(MAKE_DIRECTORY "${full_target_directory}")
            file(COPY "${source_file}" DESTINATION "${target_directory}" FILE_PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE FOLLOW_SYMLINK_CHAIN)
            file(TOUCH_NOCREATE "${target_file}")
        endif()
    endif()    
endfunction()

ly_copy("C:/Users/kcmos/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-c-auth.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/Users/kcmos/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-c-cal.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/Users/kcmos/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-c-common.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/Users/kcmos/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-c-compression.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/Users/kcmos/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-c-event-stream.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/Users/kcmos/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-c-http.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/Users/kcmos/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-c-io.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/Users/kcmos/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-c-mqtt.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/Users/kcmos/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-c-s3.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/Users/kcmos/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-checksums.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/Users/kcmos/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-cpp-sdk-core.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/Users/kcmos/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-crt-cpp.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/Users/kcmos/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-cpp-sdk-dynamodb.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/Users/kcmos/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-cpp-sdk-lambda.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/Users/kcmos/.o3de/3rdParty/packages/AWSNativeSDK-1.9.50-rev2-windows/AWSNativeSDK/bin/Release/aws-cpp-sdk-s3.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./AWSCore.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./AWSCore.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./AtomFont.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./AtomFont.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./ImGui.imguilib.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./ImGui.imguilib.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./LmbrCentral.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./LmbrCentral.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./AtomImGuiTools.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./AtomImGuiTools.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Atom_RHI_DX12.Private.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Atom_RHI_DX12.Private.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Atom_RHI_Null.Private.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Atom_RHI_Null.Private.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/Users/kcmos/.o3de/3rdParty/packages/vulkan-validationlayers-1.2.198-rev1-windows/vulkan-validationlayers/lib/release/VkLayer_khronos_validation.json" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/Users/kcmos/.o3de/3rdParty/packages/vulkan-validationlayers-1.2.198-rev1-windows/vulkan-validationlayers/lib/release/VkLayer_khronos_validation.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Atom_RHI_Vulkan.Private.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Atom_RHI_Vulkan.Private.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Atom_Feature_Common.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Atom_Feature_Common.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Atom_RHI.Private.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Atom_RHI.Private.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Atom_RPI.Private.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Atom_RPI.Private.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./AtomLyIntegration_CommonFeatures.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./AtomLyIntegration_CommonFeatures.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./AtomViewportDisplayInfo.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./AtomViewportDisplayInfo.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Atom_Bootstrap.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Atom_Bootstrap.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Atom_Component_DebugCamera.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Atom_Component_DebugCamera.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./EMotionFX.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./EMotionFX.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./EMotionFX_Atom.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./EMotionFX_Atom.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./ImguiAtom.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./ImguiAtom.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Atom_AtomBridge.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Atom_AtomBridge.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./GradientSignal.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./GradientSignal.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./AtomLyIntegration_CommonFeatures.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Atom_Bootstrap.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Camera.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Camera.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./CameraFramework.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./CameraFramework.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./EMotionFX.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./GameState.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./GameState.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./ImGui.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./ImGui.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./CrySystem.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./CrySystem.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./TextureAtlas.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./TextureAtlas.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./LyShine.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./LyShine.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Maestro.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Maestro.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./CertificateManager.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./CertificateManager.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/Users/kcmos/.o3de/3rdParty/packages/PhysX-4.1.2.29882248-rev5-windows/PhysX/shared/profile/bin/PhysX_64.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/Users/kcmos/.o3de/3rdParty/packages/PhysX-4.1.2.29882248-rev5-windows/PhysX/shared/profile/bin/PhysXCooking_64.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/Users/kcmos/.o3de/3rdParty/packages/PhysX-4.1.2.29882248-rev5-windows/PhysX/shared/profile/bin/PhysXFoundation_64.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/Users/kcmos/.o3de/3rdParty/packages/PhysX-4.1.2.29882248-rev5-windows/PhysX/shared/profile/bin/PhysXCommon_64.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/Users/kcmos/.o3de/3rdParty/packages/PhysX-4.1.2.29882248-rev5-windows/PhysX/shared/profile/bin/PhysXDevice64.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/Users/kcmos/.o3de/3rdParty/packages/PhysX-4.1.2.29882248-rev5-windows/PhysX/shared/profile/bin/PhysXGpu_64.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Multiplayer.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Multiplayer.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Multiplayer.Debug.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./Multiplayer.Debug.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./PhysX.Gem.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./PhysX.Gem.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile/Robotron_2084_O3DE.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./ExpressionEvaluation.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./ExpressionEvaluation.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./ScriptEvents.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./ScriptEvents.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./ScriptCanvas.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./ScriptCanvas.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./ScriptCanvas.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./ScriptCanvasPhysics.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./ScriptCanvasPhysics.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./ScriptEvents.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./StartingPointInput.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./StartingPointInput.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./TextureAtlas.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./WhiteBox.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/O3DE/22.05.0/bin/Windows/profile/Default/./WhiteBox.dll" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile")
ly_copy("C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile/Registry/cmake_dependencies.robotron_2084_o3de_serverlauncher.setreg" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile/Registry")
ly_copy("C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile/Registry/cmake_dependencies.robotron_2084_o3de.robotron_2084_o3de_serverlauncher.setreg" "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/bin/profile/Registry")


file(TOUCH "C:/Users/kcmos/O3DE/Projects/Robotron_2084_O3DE/build/windows/runtime_dependencies/profile/Robotron_2084_O3DE.ServerLauncher.stamp")
