#
# Copyright (c) Contributors to the Open 3D Engine Project.
# For complete copyright and license terms please see the LICENSE at the root of this distribution.
#
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
#

# Generated by O3DE

ly_add_target(
    NAME Robotron_2084_O3DE.GameLauncher IMPORTED EXECUTABLE
    NAMESPACE AZ
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            
    BUILD_DEPENDENCIES
        INTERFACE

    RUNTIME_DEPENDENCIES
        AZ::Launcher.Static
        AZ::Launcher.Game.Static
        AWSCore.Clients
        Atom.Clients
        AtomLyIntegration_CommonFeatures.Clients
        Atom_Bootstrap.Clients
        AudioSystem.Clients
        Camera.Clients
        CameraFramework.Clients
        DebugDraw.Clients
        EMotionFX.Clients
        GameState.Clients
        ImGui.Clients
        Legacy::CrySystem
        LyShine.Clients
        Maestro.Clients
        Multiplayer.Clients
        PhysX.Clients
        Robotron_2084_O3DE.Clients
        SaveData.Clients
        ScriptCanvasPhysics.Clients
        ScriptEvents.Clients
        StartingPointInput.Clients
        TextureAtlas.Clients
        WhiteBox.Clients
    TARGET_PROPERTIES
        LY_PROJECT_NAME Robotron_2084_O3DE
)



set(configs profile)
foreach(config ${configs})
    include("Platform/Windows/Default/Robotron_2084_O3DE.GameLauncher_${config}.cmake" OPTIONAL)
endforeach()

# Generated by O3DE

ly_add_target(
    NAME Robotron_2084_O3DE.ServerLauncher IMPORTED EXECUTABLE
    NAMESPACE AZ
    COMPILE_DEFINITIONS
        INTERFACE

    INCLUDE_DIRECTORIES
        INTERFACE
            
    BUILD_DEPENDENCIES
        INTERFACE

    RUNTIME_DEPENDENCIES
        AZ::Launcher.Static
        AZ::Launcher.Server.Static
        AWSCore.Servers
        Atom.Servers
        AtomLyIntegration_CommonFeatures.Servers
        Atom_Bootstrap.Servers
        Camera.Servers
        CameraFramework.Servers
        EMotionFX.Servers
        GameState.Servers
        ImGui.Servers
        Legacy::CrySystem
        LyShine.Servers
        Maestro.Servers
        Multiplayer.Servers
        PhysX.Servers
        Robotron_2084_O3DE.Servers
        ScriptCanvasPhysics.Servers
        ScriptEvents.Servers
        StartingPointInput.Servers
        TextureAtlas.Servers
        WhiteBox.Servers
    TARGET_PROPERTIES
        LY_PROJECT_NAME Robotron_2084_O3DE
)



set(configs profile)
foreach(config ${configs})
    include("Platform/Windows/Default/Robotron_2084_O3DE.ServerLauncher_${config}.cmake" OPTIONAL)
endforeach()

ly_set_gem_variant_to_load(TARGETS Robotron_2084_O3DE.GameLauncher VARIANTS Clients)
ly_set_gem_variant_to_load(TARGETS Robotron_2084_O3DE.ServerLauncher VARIANTS Servers)
