# Generated by O3DE install

set_property(TARGET Robotron_2084_O3DE.GameLauncher
    APPEND_STRING PROPERTY IMPORTED_LOCATION
        $<$<CONFIG:profile>:${LY_ROOT_FOLDER}/bin/Windows/profile/Default/./Robotron_2084_O3DE.GameLauncher.exe>
)
set_property(TARGET Robotron_2084_O3DE.GameLauncher
    PROPERTY IMPORTED_LOCATION_PROFILE
        ${LY_ROOT_FOLDER}/bin/Windows/profile/Default/./Robotron_2084_O3DE.GameLauncher.exe
)
